# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audio.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'audio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61udio.proto\x12\x05\x61udio\"E\n\tAudioData\x12\x0e\n\x06\x66ormat\x18\x01 \x01(\t\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x13\n\x0b\x61udio_bytes\x18\x03 \x01(\x0c\"$\n\rAudioResponse\x12\x13\n\x0b\x61udio_bytes\x18\x01 \x01(\x0c\x32G\n\x0c\x41udioService\x12\x37\n\x0bUploadAudio\x12\x10.audio.AudioData\x1a\x14.audio.AudioResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIODATA']._serialized_start=22
  _globals['_AUDIODATA']._serialized_end=91
  _globals['_AUDIORESPONSE']._serialized_start=93
  _globals['_AUDIORESPONSE']._serialized_end=129
  _globals['_AUDIOSERVICE']._serialized_start=131
  _globals['_AUDIOSERVICE']._serialized_end=202
# @@protoc_insertion_point(module_scope)
