[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "0.11"
libc = "0.2"
prost = "0.12"
tokio = { version = "1", features = ["full"] }
hound = "3.4.0"

[build-dependencies]
tonic-build = "0.11"